version: "3.9"

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: angular-frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: game
      DB_USER: root
      DB_PASSWORD: root
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    command: [ "sh", "-c", "echo 'Waiting for MySQL to be ready...' && sleep 30 && echo 'Starting backend...' && node --experimental-vm-modules node_modules/.bin/nest start --watch" ]

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data:
