/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ArrayGame {
  export type GameItemStruct = { id: string; bet: BigNumberish };

  export type GameItemStructOutput = [id: string, bet: bigint] & {
    id: string;
    bet: bigint;
  };
}

export interface ArrayGameInterface extends Interface {
  getFunction(
    nameOrSignature: "addGame" | "getGame" | "getGameData" | "updateGame"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addGame",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGame",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGameData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateGame",
    values: [BigNumberish, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGameData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateGame", data: BytesLike): Result;
}

export interface ArrayGame extends BaseContract {
  connect(runner?: ContractRunner | null): ArrayGame;
  waitForDeployment(): Promise<this>;

  interface: ArrayGameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addGame: TypedContractMethod<
    [_id: string, _bet: BigNumberish],
    [void],
    "nonpayable"
  >;

  getGame: TypedContractMethod<
    [index: BigNumberish],
    [[string, bigint]],
    "view"
  >;

  getGameData: TypedContractMethod<
    [],
    [ArrayGame.GameItemStructOutput[]],
    "view"
  >;

  updateGame: TypedContractMethod<
    [index: BigNumberish, _newId: string, _newBet: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addGame"
  ): TypedContractMethod<
    [_id: string, _bet: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getGame"
  ): TypedContractMethod<[index: BigNumberish], [[string, bigint]], "view">;
  getFunction(
    nameOrSignature: "getGameData"
  ): TypedContractMethod<[], [ArrayGame.GameItemStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "updateGame"
  ): TypedContractMethod<
    [index: BigNumberish, _newId: string, _newBet: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
