/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testContractSol from "./TestContract.sol";
export type { testContractSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export type { Game } from "./TestContract.sol/Game";
export { Game__factory } from "./factories/TestContract.sol/Game__factory";
