/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gameDataSol from "./GameData.sol";
export type { gameDataSol };
import type * as testGameSol from "./testGame.sol";
export type { testGameSol };
export type { ArrayGame } from "./ArrayGame";
export type { Game } from "./Game";
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { ArrayGame__factory } from "./factories/ArrayGame__factory";
export { Game__factory } from "./factories/Game__factory";
export { Lock__factory } from "./factories/Lock__factory";
export type { TestGame } from "./testGame.sol/TestGame";
export { TestGame__factory } from "./factories/testGame.sol/TestGame__factory";
