/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gameSol from "./Game.sol";
export type { gameSol };
export type { GameBase } from "./GameBase";
export type { GameLogic } from "./GameLogic";
export * as factories from "./factories";
export type { DelegateCallGameStorage } from "./Game.sol/DelegateCallGameStorage";
export { DelegateCallGameStorage__factory } from "./factories/Game.sol/DelegateCallGameStorage__factory";
export { GameBase__factory } from "./factories/GameBase__factory";
export { GameLogic__factory } from "./factories/GameLogic__factory";
